version: '3'
services:
  decidim:
    ports:
      - "$DECIDIM_PORT:3000"
    env_file:
      - secrets.env
    volumes:
      - gems-prod:/usr/local/bundle:delegated
    #environment:
      #- RAILS_ENV=development
      #- RAILS_ENV=production
#    command: ["bin/rails", "server", "-b", "ssl://decidim.iiia.csic.es:3000?key=localhost.key&cert=localhost.crt"]
    restart: on-failure
    
  pg:
    volumes:
      - pg-prod:/var/lib/postgresql/data
    env_file:
      - secrets.env
    restart: on-failure
      
  redis:
    volumes:
      - redis-prod:/data
    restart: on-failure
      
  backup:
    image: futurice/docker-volume-backup
    volumes:
      - pg-prod:/backup/pg-prod:ro    # Mount the postgresql data volume (as read-only)
      - ./decidim4cs/public:/backup/public:ro # Mount the public directory (as read-only)
      - ./decidim4cs/storage:/backup/storage:ro # Mount the storage directory (as read-only)
      - ./backups:/archive    
    restart: on-failure
    
volumes:
  gems-prod: {}
  pg-prod: {}
  redis-prod: {}
