version: '3'
services:

  nginx:
    build:
      context: docker/nginx
    volumes:
      - ./etc/nginx/user_conf.d:/etc/nginx/user_conf.d:ro
      - ./etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"

  decidim:
    build: 
      context: docker/decidim
      args:
            - USER_ID=$USER_ID
            - GROUP_ID=$GROUP_ID
    working_dir: /code
    env_file:
      - app.env
    entrypoint: /code/bin/entrypoint.sh
    command: ["bin/rails", "server", "-b", "0.0.0.0"]
    volumes:
      - .:/code
    depends_on:
      - pg
      - redis
      
  pg:
    build:
        context: docker/postgres
      
  redis:
    image: redis

